Repository jupyter/nbgrader, pull requests merged in 2018-05, with the labels that each got.

#953 update log.warn (deprecated) to log.warning
  nbgrader/apps/validateapp.py
Labels: bugfix

#954 Fix bug in find_all_files that doesn't properly ignore directories
  nbgrader/tests/utils/test_utils.py
  nbgrader/utils.py
Labels: bugfix

#947 Exclude certain assignment files from being overwritten during autograding
  nbgrader/converters/autograde.py
  nbgrader/tests/apps/test_nbgrader_autograde.py
Labels: enhancement

#955 Ignore .pytest_cache in .gitignore
  .gitignore
Labels: enhancement

#936 Switch from PhamtomJS to Firefox
  .travis.yml
  appveyor.yml
  nbgrader/docs/source/contributor_guide/installation_developer.rst
  nbgrader/server_extensions/formgrader/static/js/formgrade.js
  nbgrader/tests/nbextensions/conftest.py
  nbgrader/tests/nbextensions/formgrade_utils.py
  nbgrader/tests/nbextensions/test_assignment_list.py
  nbgrader/tests/nbextensions/test_create_assignment.py
  nbgrader/tests/nbextensions/test_formgrader.py
  nbgrader/tests/nbextensions/test_validate_assignment.py
Labels: bugfix

#957 Remove underscores from task names
  .travis.yml
  tasks.py
Labels: bugfix

#959 Allow apps to use -f and --force
  nbgrader/apps/assignapp.py
  nbgrader/apps/autogradeapp.py
  nbgrader/apps/dbapp.py
  nbgrader/apps/feedbackapp.py
  nbgrader/apps/quickstartapp.py
  nbgrader/apps/releaseapp.py
  nbgrader/apps/zipcollectapp.py
  nbgrader/tests/apps/test_nbgrader_assign.py
  nbgrader/tests/apps/test_nbgrader_autograde.py
  nbgrader/tests/apps/test_nbgrader_db.py
  nbgrader/tests/apps/test_nbgrader_feedback.py
  nbgrader/tests/apps/test_nbgrader_quickstart.py
  nbgrader/tests/apps/test_nbgrader_release.py
  nbgrader/tests/apps/test_nbgrader_zip_collect.py
Labels: enhancement

#958 Do some amount of fuzzy problem set name matching
  nbgrader/converters/base.py
  nbgrader/exchange/exchange.py
  nbgrader/exchange/fetch.py
  nbgrader/exchange/release.py
  nbgrader/exchange/submit.py
  setup.py
Labels: enhancement

#963 Add third party resources to the documentation
  nbgrader/docs/source/index.rst
  nbgrader/docs/source/user_guide/third_party.rst
Labels: docs

#964 Added "if __name__ == "__main__":"
  setup.py
Labels: refactor
