Repository jupyter/nbgrader, pull requests merged in 2018-10, with the labels that each got.

#973 Create a paper on nbgrader
  codemeta.json
  paper/paper.bib
  paper/paper.md
Labels: docs

#1005 Add random string to submission filenames for better hiding
  nbgrader/exchange/collect.py
  nbgrader/exchange/submit.py
Labels: bugfix

#1021 Fix tests, all of which are failing :(
  .travis.yml
  nbgrader/docs/source/clear_docs.py
  nbgrader/docs/source/spelling_wordlist.txt
  nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem2.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem2.html
  nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
  nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb
  nbgrader/docs/source/user_guide/managing_the_database.ipynb
  nbgrader/tests/nbextensions/conftest.py
  nbgrader/tests/nbextensions/formgrade_utils.py
  nbgrader/tests/nbextensions/test_create_assignment.py
  nbgrader/tests/nbextensions/test_formgrader.py
  nbgrader/tests/nbextensions/test_validate_assignment.py
  tasks.py
Labels: bugfix, docs

#1025 Fixing failing tests, take 2
  nbgrader/tests/nbextensions/formgrade_utils.py
Labels: bugfix

#1026 Mark test_same_part_navigation as flaky
  nbgrader/tests/nbextensions/test_formgrader.py
Labels: bugfix

#1024 Fix deprecation warning with timezones
  nbgrader/docs/source/plugins/late-plugin.rst
  nbgrader/docs/source/user_guide/autograded/bitdiddle/ps1/timestamp.txt
  nbgrader/docs/source/user_guide/autograded/hacker/ps1/timestamp.txt
  nbgrader/docs/source/user_guide/faq.rst
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/timestamp.txt
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/timestamp.txt
  nbgrader/docs/source/user_guide/submitted/bitdiddle/ps1/timestamp.txt
  nbgrader/docs/source/user_guide/submitted/hacker/ps1/timestamp.txt
  nbgrader/tests/api/test_gradebook.py
  nbgrader/tests/apps/test_nbgrader_autograde.py
  nbgrader/tests/apps/test_nbgrader_export.py
  nbgrader/tests/apps/test_nbgrader_feedback.py
  nbgrader/tests/apps/test_nbgrader_update.py
  nbgrader/utils.py
Labels: bugfix

#1002 Change to notebook directory when validating (repeat of #880)
  nbgrader/tests/apps/files/data.txt
  nbgrader/tests/apps/files/open_relative_file.ipynb
  nbgrader/tests/apps/test_nbgrader_validate.py
  nbgrader/validator.py
Labels: bugfix

#1028 Some improvements to the contributor list script
  tools/contributer_list.py
Labels: enhancement

#1029 Documentation fix to add info re: timeout errors.
  nbgrader/docs/source/user_guide/faq.rst
Labels: docs
