Repository jupyter/nbgrader, pull requests merged in 2018-12, with the labels that each got.

#1032 fix: return info of reper function is wrong in api.py
  nbgrader/api.py
  nbgrader/tests/api/test_models.py
Labels: bugfix

#1051 Remove spellcheck and enchant dependency
  .travis.yml
  appveyor.yml
  dev-requirements-windows.txt
  dev-requirements.txt
  nbgrader/docs/Makefile
  nbgrader/docs/source/conf.py
  nbgrader/docs/source/contributor_guide/documentation.rst
  nbgrader/docs/source/contributor_guide/installation_developer.rst
  nbgrader/docs/source/contributor_guide/testing.rst
  nbgrader/docs/source/spelling_wordlist.txt
  nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
  nbgrader/docs/source/user_guide/grades.csv
  nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
  nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb
  tasks.py
Labels: docs

#1053 Remove changes to sitecustomize.py and dependency on invoke
  .travis.yml
  appveyor.yml
  dev-requirements.txt
  nbgrader/docs/source/contributor_guide/documentation.rst
  nbgrader/docs/source/contributor_guide/js_dependencies.rst
  nbgrader/docs/source/contributor_guide/releasing.rst
  nbgrader/docs/source/contributor_guide/testing.rst
  tasks.py
Labels: refactor
