Repository jupyter/nbgrader, pull requests merged in 2019-11, with the labels that each got.

#1228 Fix formgrader API
  nbgrader/server_extensions/formgrader/base.py
Labels: bugfix

#1222 CourseDir.format_path: supports absolute paths in nbgrader_step
  nbgrader/coursedir.py
  nbgrader/tests/apps/test_config.py
Labels: enhancement

#1208 Improve coverage of nbgraderformat
  .coveragerc
  nbgrader/nbgraderformat/__init__.py
  nbgrader/nbgraderformat/common.py
  nbgrader/nbgraderformat/v1.py
  nbgrader/nbgraderformat/v2.py
  nbgrader/nbgraderformat/v3.py
  nbgrader/tests/__init__.py
  nbgrader/tests/nbgraderformat/test_v1.py
  nbgrader/tests/nbgraderformat/test_v2.py
  nbgrader/tests/nbgraderformat/test_v3.py
Labels: bugfix, maintenance

#1259 Remove Python 2 compatibility code
  nbgrader/apps/api.py
  nbgrader/apps/zipcollectapp.py
  nbgrader/docs/source/build_docs.py
  nbgrader/server_extensions/course_list/handlers.py
  nbgrader/tests/__init__.py
  nbgrader/tests/nbextensions/formgrade_utils.py
  nbgrader/tests/test_validator.py
  nbgrader/utils.py
  setup.py
  tools/backport_pr.py
Labels: maintenance

#1260 Set up CI with Azure Pipelines
  appveyor.yml
  appveyor/install.ps1
  appveyor/run_with_env.cmd
  azure-pipelines.yml
  nbgrader/tests/nbextensions/conftest.py
Labels: maintenance

#1266 Backport PR #1260 on branch 0.6.x
  appveyor.yml
  appveyor/install.ps1
  appveyor/run_with_env.cmd
  azure-pipelines.yml
  nbgrader/tests/nbextensions/conftest.py
Labels: backport pr

#1264 Backport PR #1245 on branch 0.6.x (Move away from using the internal Traitles API to load default configuration.)
  nbgrader/server_extensions/assignment_list/handlers.py
  nbgrader/server_extensions/course_list/handlers.py
  nbgrader/server_extensions/validate_assignment/handlers.py
Labels: backport pr

#1263 Backport PR #1227 on branch 0.6.x (Bump pytest required version to 4.5 for custom marker support)
  dev-requirements.txt
Labels: backport pr

#1265 Backport PR #1243 on branch 0.6.x (Fix project name typo)
  setup.py
Labels: backport pr

#1262 Backport PR #1208 on branch 0.6.x (Improve coverage of nbgraderformat)
  .coveragerc
  nbgrader/nbgraderformat/__init__.py
  nbgrader/nbgraderformat/common.py
  nbgrader/nbgraderformat/v1.py
  nbgrader/nbgraderformat/v2.py
  nbgrader/nbgraderformat/v3.py
  nbgrader/tests/__init__.py
  nbgrader/tests/nbgraderformat/test_v1.py
  nbgrader/tests/nbgraderformat/test_v2.py
  nbgrader/tests/nbgraderformat/test_v3.py
Labels: backport pr

#1270 Add requirements for readthedocs
  readthedocs-requirements.txt
  readthedocs.yaml
Labels: docs, maintenance

#1269 Backport PR #1267 on branch 0.6.x (Improve the error message on the assignments page)
  nbgrader/server_extensions/assignment_list/handlers.py
Labels: backport pr

#1276 remove db_assignments db_students
  nbgrader/apps/baseapp.py
  nbgrader/apps/quickstartapp.py
  nbgrader/converters/autograde.py
  nbgrader/converters/generate_assignment.py
  nbgrader/coursedir.py
  nbgrader/docs/source/user_guide/managing_the_database.ipynb
  nbgrader/tests/apps/test_nbgrader_autograde.py
  nbgrader/tests/apps/test_nbgrader_export.py
  nbgrader/tests/apps/test_nbgrader_fetchfeedback.py
  nbgrader/tests/apps/test_nbgrader_generate_assignment.py
  nbgrader/tests/apps/test_nbgrader_generate_feedback.py
  nbgrader/tests/apps/test_nbgrader_releasefeedback.py
  nbgrader/tests/apps/test_nbgrader_update.py
  nbgrader/tests/apps/test_nbgrader_zip_collect.py
  nbgrader/tests/nbextensions/conftest.py
Labels: maintenance, refactor

#1272 Improve test coverage in auth folder
  nbgrader/auth/base.py
  nbgrader/auth/jupyterhub.py
  nbgrader/server_extensions/course_list/handlers.py
  nbgrader/tests/test_auth.py
Labels: maintenance

#1277 Backport PR #1272 on branch 0.6.x (Improve test coverage in auth folder)
  nbgrader/auth/base.py
  nbgrader/auth/jupyterhub.py
  nbgrader/server_extensions/course_list/handlers.py
  nbgrader/tests/test_auth.py
Labels: backport pr

#1278 Fix course list hanging when exchange has not been created
  nbgrader/nbextensions/course_list/course_list.js
  nbgrader/server_extensions/course_list/handlers.py
Labels: bugfix

#1279 Backport PR #1278 on branch 0.6.x (Fix course list hanging when exchange has not been created )
  nbgrader/nbextensions/course_list/course_list.js
  nbgrader/server_extensions/course_list/handlers.py
Labels: backport pr

#1280 Fix inappropriate use of sum with newer sqlite
  .travis.yml
  azure-pipelines.yml
  nbgrader/api.py
  nbgrader/tests/api/test_models.py
Labels: bugfix

#1284 Backport PR #1280 on branch 0.6.x (Fix inappropriate use of sum with newer sqlite)
  .travis.yml
  azure-pipelines.yml
  nbgrader/api.py
  nbgrader/tests/api/test_models.py
Labels: backport pr

#1285 Backport PR #1228 on branch 0.6.x (Fix formgrader API)
  nbgrader/server_extensions/formgrader/base.py
Labels: backport pr

#1249 timestamp_format raises an exception
  nbgrader/exchange/exchange.py
Labels: bugfix

#1287 Add mypy for type checking
  .gitignore
  dev-requirements.txt
  mypy.ini
  tasks.py
Labels: maintenance

#1286 Create 0.6.1 release
  nbgrader/_version.py
  nbgrader/docs/source/changelog.rst
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem2.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem2.html
  nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
  nbgrader/nbextensions/assignment_list/main.js
  nbgrader/nbextensions/course_list/main.js
  nbgrader/nbextensions/validate_assignment/main.js
Labels: maintenance

#1289 Backport PR #1249 on branch 0.6.x (timestamp_format raises an exception)
  nbgrader/exchange/exchange.py
Labels: backport pr

#1290 Backport PR #1288 on branch 0.6.x (Fixes #1283: Replace AppVeyor badge with Azure Devops badge)
  README.md
Labels: backport pr

#1282 Further type annotations across the codebase
  nbgrader/apps/autogradeapp.py
  nbgrader/apps/baseapp.py
  nbgrader/apps/generateassignmentapp.py
  nbgrader/apps/nbgraderapp.py
  nbgrader/auth/base.py
  nbgrader/auth/jupyterhub.py
  nbgrader/converters/autograde.py
  nbgrader/converters/base.py
  nbgrader/converters/generate_assignment.py
  nbgrader/nbgraderformat/common.py
  nbgrader/nbgraderformat/v1.py
  nbgrader/nbgraderformat/v2.py
  nbgrader/nbgraderformat/v3.py
  nbgrader/plugins/base.py
  nbgrader/plugins/export.py
  nbgrader/plugins/latesubmission.py
  nbgrader/plugins/zipcollect.py
  nbgrader/preprocessors/checkcellmetadata.py
  nbgrader/preprocessors/clearhiddentests.py
  nbgrader/preprocessors/clearmarkingscheme.py
  nbgrader/preprocessors/clearsolutions.py
  nbgrader/preprocessors/computechecksums.py
  nbgrader/preprocessors/deduplicateids.py
  nbgrader/preprocessors/execute.py
  nbgrader/preprocessors/getgrades.py
  nbgrader/preprocessors/headerfooter.py
  nbgrader/preprocessors/latesubmissions.py
  nbgrader/preprocessors/limitoutput.py
  nbgrader/preprocessors/lockcells.py
  nbgrader/preprocessors/overwritecells.py
  nbgrader/preprocessors/overwritekernelspec.py
  nbgrader/preprocessors/saveautogrades.py
  nbgrader/preprocessors/savecells.py
  nbgrader/tests/__init__.py
  nbgrader/tests/api/test_gradebook.py
  nbgrader/tests/apps/base.py
  nbgrader/tests/apps/conftest.py
  nbgrader/tests/apps/test_nbgrader_autograde.py
  nbgrader/tests/test_auth.py
  nbgrader/tests/test_validator.py
Labels: maintenance, refactor

#1281 Demos using Python3
  demos/demo_multiple_classes/setup_demo.sh
  demos/restart_demo.sh
Labels: bugfix
