Repository jupyter/nbgrader, pull requests merged in 2019-06, with the labels that each got.

#1119 added a sanatizing step to the doc creation.
  nbgrader/docs/source/clear_docs.py
  nbgrader/docs/source/user_guide/autograded/bitdiddle/ps1/problem1.ipynb
  nbgrader/docs/source/user_guide/autograded/hacker/ps1/problem1.ipynb
  nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem2.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem2.html
  nbgrader/docs/source/user_guide/grades.csv
  nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
  nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb
  nbgrader/docs/source/user_guide/managing_the_database.ipynb
Labels: docs, enhancement

#1118 Integrate course_id into the api and apps
  nbgrader/apps/api.py
  nbgrader/apps/assignapp.py
  nbgrader/apps/autogradeapp.py
  nbgrader/apps/baseapp.py
  nbgrader/apps/collectapp.py
  nbgrader/apps/dbapp.py
  nbgrader/apps/exportapp.py
  nbgrader/apps/fetchapp.py
  nbgrader/apps/listapp.py
  nbgrader/apps/quickstartapp.py
  nbgrader/apps/releaseapp.py
  nbgrader/apps/submitapp.py
  nbgrader/converters/assign.py
  nbgrader/converters/autograde.py
  nbgrader/coursedir.py
  nbgrader/docs/source/api/high_level_api.rst
  nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
  nbgrader/docs/source/user_guide/philosophy.rst
  nbgrader/exchange/collect.py
  nbgrader/exchange/exchange.py
  nbgrader/exchange/fetch.py
  nbgrader/exchange/list.py
  nbgrader/exchange/release.py
  nbgrader/exchange/submit.py
  nbgrader/server_extensions/assignment_list/handlers.py
  nbgrader/tests/apps/test_api.py
  nbgrader/tests/nbextensions/conftest.py
Labels: refactor

#1113 Add a course list extension that shows all courses an instructor can manage
  nbgrader/__init__.py
  nbgrader/auth/jupyterhub.py
  nbgrader/docs/source/user_guide/installation.rst
  nbgrader/nbextensions/course_list/course_list.css
  nbgrader/nbextensions/course_list/course_list.js
  nbgrader/nbextensions/course_list/main.js
  nbgrader/server_extensions/course_list/__init__.py
  nbgrader/server_extensions/course_list/handlers.py
  nbgrader/server_extensions/formgrader/apihandlers.py
  nbgrader/tests/apps/test_nbgrader_extension.py
  nbgrader/tests/nbextensions/conftest.py
  nbgrader/tests/nbextensions/test_course_list.py
Labels: enhancement

#1122 Fix incorrect usage of Exchange.course_id
  nbgrader/server_extensions/course_list/handlers.py
Labels: bugfix

#1124 Only run nbextensions tests on oldest and newest versions of python
  .travis.yml
Labels: maintenance

#1121 Fix logfile
  nbgrader/apps/baseapp.py
  nbgrader/docs/source/configuration/jupyterhub_config.rst
  nbgrader/tests/apps/test_nbgrader.py
Labels: bugfix

#1125 Check that the course directory is a subdirectory of the notebook dir
  nbgrader/server_extensions/formgrader/apihandlers.py
  nbgrader/server_extensions/formgrader/base.py
  nbgrader/server_extensions/formgrader/formgrader.py
  nbgrader/server_extensions/formgrader/handlers.py
Labels: bugfix

#1126 Remove the third party resources page
  nbgrader/docs/source/index.rst
  nbgrader/docs/source/user_guide/third_party.rst
Labels: docs

#1127 Better documentation of nbgrader_config.py
  nbgrader/docs/source/build_docs.py
  nbgrader/docs/source/configuration/jupyterhub_config.rst
  nbgrader/docs/source/configuration/nbgrader_config.rst
  nbgrader/docs/source/configuration/student_version.rst
  nbgrader/docs/source/index.rst
Labels: docs

#1001 Allow setting a different assignment dir for students than the root notebook directory
  nbgrader/exchange/exchange.py
  nbgrader/exchange/fetch.py
  nbgrader/server_extensions/assignment_list/handlers.py
Labels: enhancement

#1135 section on grading in docker container
  nbgrader/docs/source/user_guide/advanced.rst
Labels: docs

#1123 Ensure course directory root path has no trailing slashes
  nbgrader/coursedir.py
  nbgrader/tests/apps/test_nbgrader_assign.py
Labels: bugfix

#1138 Ensure that cell type changes result in valid nbgrader metadata
  nbgrader/nbextensions/create_assignment/main.js
  nbgrader/tests/nbextensions/test_create_assignment.py
Labels: UX/UI, bugfix

#1114 Documentation for multiple classes
  nbgrader/docs/source/configuration/jupyterhub_config.rst
  nbgrader/docs/source/user_guide/third_party.rst
Labels: docs

#1111 Optional consistency check between owner and student_id upon collect
  nbgrader/exchange/collect.py
  nbgrader/tests/apps/test_nbgrader_collect.py
Labels: enhancement

#1139 Additional docs sanitization
  nbgrader/docs/source/clear_docs.py
  nbgrader/docs/source/user_guide/autograded/bitdiddle/ps1/problem1.ipynb
  nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem1.html
  nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
  nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb
Labels: docs, maintenance

#1140 A few more updates to the docs for multiple classes
  nbgrader/docs/source/configuration/images/multiple_classes.png
  nbgrader/docs/source/configuration/images/one_class_multiple_instructors.png
  nbgrader/docs/source/configuration/images/one_class_one_instructor.png
  nbgrader/docs/source/configuration/jupyterhub_config.rst
  nbgrader/docs/source/user_guide/advanced.rst
  nbgrader/docs/source/user_guide/faq.rst
Labels: docs

#1147 Add test to ensure that db upgrade succeeds before running assign
  nbgrader/alembic/versions/167914646830_added_task_cells.py
  nbgrader/tests/apps/test_nbgrader_db.py
Labels: bugfix

#1099 Add course table, add course_id column to assignment
  nbgrader/alembic/versions/e43177bfe90b_added_course_table_and_relationships.py
  nbgrader/api.py
  nbgrader/tests/api/test_gradebook.py
Labels: enhancement, refactor

#1131 Better support for multiple classes
  dev-requirements.txt
  nbgrader/__init__.py
  nbgrader/alembic/versions/e43177bfe90b_added_course_table_and_relationships.py
  nbgrader/api.py
  nbgrader/apps/api.py
  nbgrader/apps/assignapp.py
  nbgrader/apps/autogradeapp.py
  nbgrader/apps/baseapp.py
  nbgrader/apps/collectapp.py
  nbgrader/apps/dbapp.py
  nbgrader/apps/exportapp.py
  nbgrader/apps/fetchapp.py
  nbgrader/apps/fetchfeedbackapp.py
  nbgrader/apps/listapp.py
  nbgrader/apps/quickstartapp.py
  nbgrader/apps/releaseapp.py
  nbgrader/apps/releasefeedbackapp.py
  nbgrader/apps/submitapp.py
  nbgrader/auth/__init__.py
  nbgrader/auth/base.py
  nbgrader/auth/jupyterhub.py
  nbgrader/converters/assign.py
  nbgrader/converters/autograde.py
  nbgrader/coursedir.py
  nbgrader/docs/source/api/high_level_api.rst
  nbgrader/docs/source/configuration/images/multiple_classes.png
  nbgrader/docs/source/configuration/images/one_class_multiple_instructors.png
  nbgrader/docs/source/configuration/images/one_class_one_instructor.png
  nbgrader/docs/source/configuration/jupyterhub_config.rst
  nbgrader/docs/source/configuration/nbgrader_config.rst
  nbgrader/docs/source/user_guide/advanced.rst
  nbgrader/docs/source/user_guide/faq.rst
  nbgrader/docs/source/user_guide/installation.rst
  nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
  nbgrader/docs/source/user_guide/philosophy.rst
  nbgrader/exchange/collect.py
  nbgrader/exchange/exchange.py
  nbgrader/exchange/fetch.py
  nbgrader/exchange/fetch_feedback.py
  nbgrader/exchange/list.py
  nbgrader/exchange/release.py
  nbgrader/exchange/release_feedback.py
  nbgrader/exchange/submit.py
  nbgrader/nbextensions/course_list/course_list.css
  nbgrader/nbextensions/course_list/course_list.js
  nbgrader/nbextensions/course_list/main.js
  nbgrader/server_extensions/assignment_list/handlers.py
  nbgrader/server_extensions/course_list/__init__.py
  nbgrader/server_extensions/course_list/handlers.py
  nbgrader/server_extensions/formgrader/apihandlers.py
  nbgrader/server_extensions/formgrader/base.py
  nbgrader/server_extensions/formgrader/formgrader.py
  nbgrader/tests/api/test_gradebook.py
  nbgrader/tests/apps/test_api.py
  nbgrader/tests/apps/test_nbgrader_extension.py
  nbgrader/tests/nbextensions/conftest.py
  nbgrader/tests/nbextensions/test_course_list.py
  nbgrader/tests/test_auth.py
  nbgrader/utils.py
Labels: enhancement

#1137 Rename "nbgrader assign" to "nbgrader generate_assignment"
  nbgrader/apps/__init__.py
  nbgrader/apps/api.py
  nbgrader/apps/assignapp.py
  nbgrader/apps/autogradeapp.py
  nbgrader/apps/generateassignmentapp.py
  nbgrader/apps/nbgraderapp.py
  nbgrader/apps/quickstartapp.py
  nbgrader/apps/releaseapp.py
  nbgrader/converters/__init__.py
  nbgrader/converters/assign.py
  nbgrader/converters/autograde.py
  nbgrader/converters/base.py
  nbgrader/converters/generate_assignment.py
  nbgrader/docs/source/api/high_level_api.rst
  nbgrader/docs/source/build_docs.py
  nbgrader/docs/source/command_line_tools/index.rst
  nbgrader/docs/source/configuration/jupyterhub_config.rst
  nbgrader/docs/source/configuration/student_version.rst
  nbgrader/docs/source/contributor_guide/metadata.rst
  nbgrader/docs/source/contributor_guide/testing.rst
  nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
  nbgrader/docs/source/user_guide/faq.rst
  nbgrader/docs/source/user_guide/highlights.rst
  nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
  nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb
  nbgrader/exchange/release.py
  nbgrader/nbgraderformat/v2.json
  nbgrader/nbgraderformat/v3.json
  nbgrader/server_extensions/formgrader/apihandlers.py
  nbgrader/tests/apps/test_api.py
  nbgrader/tests/apps/test_nbgrader_autograde.py
  nbgrader/tests/apps/test_nbgrader_db.py
  nbgrader/tests/apps/test_nbgrader_export.py
  nbgrader/tests/apps/test_nbgrader_feedback.py
  nbgrader/tests/apps/test_nbgrader_generate_assignment.py
  nbgrader/tests/apps/test_nbgrader_quickstart.py
  nbgrader/tests/apps/test_nbgrader_update.py
  nbgrader/tests/apps/test_nbgrader_zip_collect.py
  nbgrader/tests/nbextensions/test_assignment_list.py
  nbgrader/tests/nbextensions/test_formgrader.py
Labels: refactor

#1145 Rename nbgrader feedback to nbgrader generate_feedback
  nbgrader/apps/__init__.py
  nbgrader/apps/api.py
  nbgrader/apps/feedbackapp.py
  nbgrader/apps/generatefeedbackapp.py
  nbgrader/apps/nbgraderapp.py
  nbgrader/apps/releasefeedbackapp.py
  nbgrader/converters/__init__.py
  nbgrader/converters/base.py
  nbgrader/converters/feedback.py
  nbgrader/converters/generate_feedback.py
  nbgrader/docs/source/build_docs.py
  nbgrader/docs/source/command_line_tools/index.rst
  nbgrader/docs/source/configuration/jupyterhub_config.rst
  nbgrader/docs/source/configuration/student_version.rst
  nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
  nbgrader/docs/source/user_guide/faq.rst
  nbgrader/docs/source/user_guide/highlights.rst
  nbgrader/tests/apps/test_nbgrader_fetchfeedback.py
  nbgrader/tests/apps/test_nbgrader_generate_feedback.py
  nbgrader/tests/apps/test_nbgrader_releasefeedback.py
Labels: refactor

#1151 Rename 'nbgrader release' to 'nbgrader release_assignment'
  nbgrader/apps/__init__.py
  nbgrader/apps/api.py
  nbgrader/apps/nbgraderapp.py
  nbgrader/apps/releaseapp.py
  nbgrader/apps/releaseassignmentapp.py
  nbgrader/apps/releasefeedbackapp.py
  nbgrader/docs/source/build_docs.py
  nbgrader/docs/source/command_line_tools/index.rst
  nbgrader/docs/source/configuration/jupyterhub_config.rst
  nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
  nbgrader/docs/source/user_guide/faq.rst
  nbgrader/docs/source/user_guide/highlights.rst
  nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
  nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb
  nbgrader/exchange/__init__.py
  nbgrader/exchange/release.py
  nbgrader/exchange/release_assignment.py
  nbgrader/server_extensions/formgrader/apihandlers.py
  nbgrader/tests/apps/test_api.py
  nbgrader/tests/apps/test_nbgrader_collect.py
  nbgrader/tests/apps/test_nbgrader_fetch.py
  nbgrader/tests/apps/test_nbgrader_fetchfeedback.py
  nbgrader/tests/apps/test_nbgrader_list.py
  nbgrader/tests/apps/test_nbgrader_releaseassignment.py
  nbgrader/tests/apps/test_nbgrader_submit.py
  nbgrader/tests/nbextensions/test_assignment_list.py
Labels: refactor
