Repository jupyter/nbgrader, pull requests merged in 2019-08, with the labels that each got.

#1090 partial credit for autograde test cells
  nbgrader/preprocessors/saveautogrades.py
  nbgrader/tests/utils/test_utils.py
  nbgrader/utils.py
  nbgrader/validator.py
Labels: enhancement

#1000 Allow instructors to share files via shared group id
  nbgrader/converters/base.py
  nbgrader/converters/generate_assignment.py
  nbgrader/converters/generate_feedback.py
  nbgrader/coursedir.py
  nbgrader/exchange/exchange.py
  nbgrader/exchange/release_assignment.py
  nbgrader/exchange/release_feedback.py
  nbgrader/tests/apps/base.py
  nbgrader/tests/apps/test_nbgrader_autograde.py
  nbgrader/tests/apps/test_nbgrader_collect.py
  nbgrader/tests/apps/test_nbgrader_generate_assignment.py
  nbgrader/tests/apps/test_nbgrader_generate_feedback.py
  nbgrader/tests/apps/test_nbgrader_releaseassignment.py
  nbgrader/tests/apps/test_nbgrader_releasefeedback.py
Labels: enhancement

#1169 Fix minor typo in js extension helper text
  nbgrader/nbextensions/create_assignment/main.js
Labels: docs

#1180 Fix versions of pytest and nbconvert
  dev-requirements.txt
  setup.py
Labels: maintenance

#1182 Make 0.5.6 release
  nbgrader/_version.py
  nbgrader/docs/source/changelog.rst
  nbgrader/nbextensions/assignment_list/main.js
  nbgrader/nbextensions/validate_assignment/main.js
  setup.py
Labels: maintenance

#1164 assignment_dir: Add into several missing places
  nbgrader/exchange/fetch_feedback.py
  nbgrader/exchange/list.py
  nbgrader/exchange/submit.py
Labels: bugfix

#1186 Remove student_id and change root to cache, permission check to only execute
  nbgrader/exchange/fetch_feedback.py
  nbgrader/tests/apps/test_api.py
  nbgrader/tests/apps/test_nbgrader_fetchfeedback.py
Labels: bugfix

#1179 Add CourseDir.student_id_exclude option to exclude students
  nbgrader/converters/base.py
  nbgrader/coursedir.py
  nbgrader/exchange/release_feedback.py
  nbgrader/tests/apps/test_nbgrader_autograde.py
  nbgrader/tests/apps/test_nbgrader_generate_feedback.py
  nbgrader/tests/apps/test_nbgrader_releasefeedback.py
Labels: enhancement

#1183 Feedback: update fetch_feedback command line help
  nbgrader/apps/fetchfeedbackapp.py
Labels: docs

#1190 Add JupyterHub demos
  demos/README.md
  demos/demo_multiple_classes/course101_nbgrader_config.py
  demos/demo_multiple_classes/course123_nbgrader_config.py
  demos/demo_multiple_classes/global_nbgrader_config.py
  demos/demo_multiple_classes/jupyterhub_config.py
  demos/demo_multiple_classes/setup_demo.sh
  demos/demo_one_class_multiple_graders/course101_nbgrader_config.py
  demos/demo_one_class_multiple_graders/global_nbgrader_config.py
  demos/demo_one_class_multiple_graders/jupyterhub_config.py
  demos/demo_one_class_multiple_graders/setup_demo.sh
  demos/demo_one_class_one_grader/instructor_nbgrader_config.py
  demos/demo_one_class_one_grader/jupyterhub_config.py
  demos/demo_one_class_one_grader/setup_demo.sh
  demos/deploy_demos.sh
  demos/restart_demo.sh
  demos/utils.sh
Labels: docs, enhancement

#1191 Allow access to formgrader when not using JuptyerHub auth
  nbgrader/auth/jupyterhub.py
  nbgrader/docs/source/configuration/jupyterhub_config.rst
  nbgrader/docs/source/contributor_guide/releasing.rst
  nbgrader/exchange/list.py
  nbgrader/server_extensions/course_list/handlers.py
Labels: bugfix, docs

#1192 Create 0.6.0 release
  nbgrader/_version.py
  nbgrader/apps/fetchassignmentapp.py
  nbgrader/apps/fetchfeedbackapp.py
  nbgrader/docs/source/build_docs.py
  nbgrader/docs/source/changelog.rst
  nbgrader/docs/source/configuration/jupyterhub_config.rst
  nbgrader/docs/source/user_guide/faq.rst
  nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
  nbgrader/nbextensions/assignment_list/main.js
  nbgrader/nbextensions/course_list/main.js
  nbgrader/nbextensions/validate_assignment/main.js
  tools/contributer_list.py
  tools/gh_api.py
Labels: maintenance

#1194 Update releasing instructions
  nbgrader/docs/source/contributor_guide/releasing.rst
  tools/release.py
Labels: docs

#1196 Fix config warning in ExchangeReleaseAssignment
  nbgrader/exchange/release_assignment.py
Labels: bugfix

#1197 Do not duplicate assignments when fetching feedback
  nbgrader/nbextensions/assignment_list/assignment_list.js
Labels: bugfix

#1198 Backport PR #1196 on branch 0.6.x (Fix config warning in ExchangeReleaseAssignment)
  nbgrader/exchange/release_assignment.py
Labels: backport pr

#1199 Backport PR #1197 on branch 0.6.x (Do not duplicate assignments when fetching feedback)
  nbgrader/nbextensions/assignment_list/assignment_list.js
Labels: backport pr

#1200 Associate feedback files with unique submission attempts
  nbgrader/exchange/fetch_feedback.py
  nbgrader/exchange/list.py
  nbgrader/exchange/release_feedback.py
  nbgrader/nbextensions/assignment_list/assignment_list.js
  nbgrader/server_extensions/assignment_list/handlers.py
  nbgrader/tests/apps/test_api.py
  nbgrader/tests/apps/test_nbgrader_list.py
  nbgrader/tests/apps/test_nbgrader_releasefeedback.py
  nbgrader/tests/nbextensions/test_assignment_list.py
  nbgrader/utils.py
Labels: bugfix, refactor

#1203 Backport PR #1200 on branch 0.6.x (Associate feedback files with unique submission attempts)
  nbgrader/exchange/fetch_feedback.py
  nbgrader/exchange/list.py
  nbgrader/exchange/release_feedback.py
  nbgrader/nbextensions/assignment_list/assignment_list.js
  nbgrader/server_extensions/assignment_list/handlers.py
  nbgrader/tests/apps/test_api.py
  nbgrader/tests/apps/test_nbgrader_list.py
  nbgrader/tests/apps/test_nbgrader_releasefeedback.py
  nbgrader/tests/nbextensions/test_assignment_list.py
  nbgrader/utils.py
Labels: backport pr

#1205 Check for newer feedback in nbgrader list
  nbgrader/exchange/list.py
  nbgrader/nbextensions/assignment_list/assignment_list.js
  nbgrader/tests/apps/test_nbgrader_list.py
Labels: bugfix

#1204 Force generate feedback by default in API
  nbgrader/apps/api.py
  nbgrader/tests/apps/test_api.py
Labels: bugfix

#1206 Backport PR #1205 on branch 0.6.x (Check for newer feedback in nbgrader list)
  nbgrader/exchange/list.py
  nbgrader/nbextensions/assignment_list/assignment_list.js
  nbgrader/tests/apps/test_nbgrader_list.py
Labels: backport pr

#1207 Backport PR #1204 on branch 0.6.x (Force generate feedback by default in API)
  nbgrader/apps/api.py
  nbgrader/tests/apps/test_api.py
Labels: backport pr
