Repository jupyter/nbgrader, pull requests merged in 2019-05, with the labels that each got.

#1061 Set env var NBGRADER_VALIDATING when validating
  nbgrader/utils.py
  nbgrader/validator.py
Labels: enhancement

#1064 Validate all cells
  nbgrader/validator.py
Labels: enhancement

#967 Added note in FAQ about changing cell ids
  nbgrader/docs/source/user_guide/faq.rst
Labels: docs, needs work

#1080 compatibility with SQLAlchemy 1.3+
  nbgrader/api.py
Labels: bugfix

#1084 Fix miscellaneous bugs
  nbgrader/tests/nbextensions/files/blank.ipynb
  nbgrader/tests/nbextensions/files/old-schema.ipynb
  nbgrader/tests/nbextensions/files/open_relative_file.ipynb
  nbgrader/tests/nbextensions/files/submitted-answer-cell-type-changed.ipynb
  nbgrader/tests/nbextensions/files/submitted-changed.ipynb
  nbgrader/tests/nbextensions/files/submitted-grade-cell-changed.ipynb
  nbgrader/tests/nbextensions/files/submitted-grade-cell-type-changed.ipynb
  nbgrader/tests/nbextensions/files/submitted-locked-cell-changed.ipynb
  nbgrader/tests/nbextensions/files/submitted-unchanged.ipynb
  nbgrader/tests/nbextensions/files/task.ipynb
  nbgrader/tests/nbextensions/test_create_assignment.py
  nbgrader/tests/preprocessors/files/bad-markdown-cell-1.ipynb
  nbgrader/tests/preprocessors/files/bad-markdown-cell-2.ipynb
  nbgrader/tests/preprocessors/files/blank-grade-id.ipynb
  nbgrader/tests/preprocessors/files/blank-points.ipynb
  nbgrader/tests/preprocessors/files/cell-type-changed.ipynb
  nbgrader/tests/preprocessors/files/duplicate-grade-ids.ipynb
  nbgrader/tests/preprocessors/files/header.ipynb
  nbgrader/tests/preprocessors/files/infinite-recursion.ipynb
  nbgrader/tests/preprocessors/files/long-output.ipynb
  nbgrader/tests/preprocessors/files/manually-graded-code-cell.ipynb
  nbgrader/tests/preprocessors/files/no-cell-type.ipynb
  nbgrader/tests/preprocessors/files/submitted-answer-cell-type-changed.ipynb
  nbgrader/tests/preprocessors/files/submitted-changed.ipynb
  nbgrader/tests/preprocessors/files/submitted-grade-cell-changed.ipynb
  nbgrader/tests/preprocessors/files/submitted-grade-cell-type-changed.ipynb
  nbgrader/tests/preprocessors/files/submitted-locked-cell-changed.ipynb
  nbgrader/tests/preprocessors/files/submitted-unchanged.ipynb
  nbgrader/tests/preprocessors/files/test.ipynb
  nbgrader/tests/preprocessors/files/test_taskcell.ipynb
  pytest.ini
  setup.py
  tasks.py
Labels: bugfix, maintenance

#1075 Give ExecutePreprocessor the Traitlets config during validation
  nbgrader/validator.py
Labels: bugfix

#1071 student and assignment selection in exportapp implemented
  nbgrader/apps/exportapp.py
  nbgrader/plugins/export.py
  nbgrader/tests/apps/test_nbgrader_export.py
Labels: enhancement

#1088 Remove version requirement from urllib3
  setup.py
Labels: maintenance

#1040 Restrict access for students to different courses
  nbgrader/api.py
  nbgrader/apps/api.py
  nbgrader/apps/dbapp.py
  nbgrader/exchange/exchange.py
  nbgrader/exchange/fetch.py
  nbgrader/exchange/list.py
  nbgrader/exchange/submit.py
  nbgrader/server_extensions/assignment_list/handlers.py
  nbgrader/utils.py
Labels: Edinburgh-Hackathon, enhancement

#1094 Update license
  COPYING.md
  LICENSE
Labels: maintenance

#1093 Add authentication plugin support
  dev-requirements.txt
  nbgrader/api.py
  nbgrader/apps/api.py
  nbgrader/apps/baseapp.py
  nbgrader/apps/collectapp.py
  nbgrader/apps/dbapp.py
  nbgrader/apps/fetchapp.py
  nbgrader/apps/listapp.py
  nbgrader/apps/nbgraderapp.py
  nbgrader/apps/releaseapp.py
  nbgrader/apps/submitapp.py
  nbgrader/auth/__init__.py
  nbgrader/auth/base.py
  nbgrader/auth/jupyterhub.py
  nbgrader/exchange/exchange.py
  nbgrader/exchange/fetch.py
  nbgrader/exchange/list.py
  nbgrader/exchange/submit.py
  nbgrader/server_extensions/assignment_list/handlers.py
  nbgrader/server_extensions/formgrader/base.py
  nbgrader/server_extensions/formgrader/formgrader.py
  nbgrader/tests/test_auth.py
  nbgrader/utils.py
Labels: Edinburgh-Hackathon, enhancement, refactor

#1098 Customizable student ID in `nbgrader submit`
  nbgrader/apps/submitapp.py
  nbgrader/coursedir.py
  nbgrader/exchange/submit.py
  nbgrader/tests/apps/test_nbgrader_submit.py
Labels: enhancement

#1100 Run test in the `python` group in parallel using pytest-xdist
  dev-requirements.txt
  tasks.py
Labels: Edinburgh-Hackathon, maintenance

#1102 Only build docs with one version of python
  .travis.yml
  appveyor.yml
Labels: Edinburgh-Hackathon, docs, maintenance

#1101 Add jupyter education book to third party resources
  nbgrader/docs/source/user_guide/third_party.rst
Labels: Edinburgh-Hackathon, docs

#1109 naming the temporary directories in tests
  nbgrader/tests/apps/conftest.py
Labels: Edinburgh-Hackathon, maintenance

#1106 Remove testing of python 3.4
  .travis.yml
  setup.py
Labels: Edinburgh-Hackathon, maintenance

#1036 Add a general lms user id column to the student table
  nbgrader/alembic/versions/282d30a0218e_adds_lms_user_id_column_to_student_table.py
  nbgrader/api.py
  nbgrader/apps/api.py
  nbgrader/apps/dbapp.py
  nbgrader/docs/source/api/models.rst
  nbgrader/tests/api/test_models.py
  nbgrader/tests/apps/test_api.py
  nbgrader/tests/apps/test_nbgrader_db.py
Labels: Edinburgh-Hackathon, enhancement

#1105 Remove extra keys in nbgrader metadata and better schema mismatch errors
  nbgrader/apps/updateapp.py
  nbgrader/apps/validateapp.py
  nbgrader/converters/base.py
  nbgrader/nbgraderformat/__init__.py
  nbgrader/nbgraderformat/common.py
  nbgrader/nbgraderformat/v1.py
  nbgrader/nbgraderformat/v2.py
  nbgrader/nbgraderformat/v3.py
  nbgrader/server_extensions/validate_assignment/handlers.py
  nbgrader/tests/apps/files/too-new.ipynb
  nbgrader/tests/apps/test_nbgrader_update.py
  nbgrader/tests/nbgraderformat/test_v2.py
  nbgrader/tests/nbgraderformat/test_v3.py
Labels: Edinburgh-Hackathon, bugfix

#1110 Systematic use of utils.get_username instead of $USER
  nbgrader/tests/apps/test_nbgrader_collect.py
  nbgrader/tests/apps/test_nbgrader_list.py
  nbgrader/tests/apps/test_nbgrader_submit.py
  nbgrader/tests/utils/conftest.py
  nbgrader/tests/utils/test_utils.py
Labels: Edinburgh-Hackathon, maintenance

#1108 Extended support for filtering files copied in the exchange
  nbgrader/coursedir.py
  nbgrader/exchange/exchange.py
  nbgrader/tests/apps/test_nbgrader_submit.py
  nbgrader/tests/utils/test_utils.py
  nbgrader/utils.py
Labels: Edinburgh-Hackathon, enhancement

#1112 Locate all configurable classes for generate_config subcommand
  nbgrader/apps/baseapp.py
  nbgrader/apps/generateconfigapp.py
  nbgrader/apps/nbgraderapp.py
  nbgrader/tests/apps/test_nbgrader_generate_config.py
Labels: Edinburgh-Hackathon, bugfix

#1115 Fix typo in tmp filename prefix in conftest.py
  nbgrader/tests/apps/conftest.py
Labels: maintenance

#1116 Autograde & Assign: create missing students/assignments by default
  nbgrader/apps/assignapp.py
  nbgrader/apps/autogradeapp.py
  nbgrader/converters/assign.py
  nbgrader/converters/autograde.py
  nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
  nbgrader/tests/apps/test_api.py
  nbgrader/tests/apps/test_nbgrader_assign.py
  nbgrader/tests/apps/test_nbgrader_autograde.py
  nbgrader/tests/apps/test_nbgrader_db.py
Labels: Edinburgh-Hackathon, bugfix
