Repository jupyter/nbgrader, pull requests merged in 2020-05, with the labels that each got.

#1320 Add nbgrader collect --before-duedate option
  nbgrader/apps/collectapp.py
  nbgrader/exchange/collect.py
  nbgrader/tests/apps/test_nbgrader_collect.py
Labels: needs review

#1315 ExchangeFetchAssignment deleting the wrong config
  nbgrader/exchange/fetch_assignment.py
Labels: bugfix

#1238 Pluggable exchange
  nbgrader/apps/api.py
  nbgrader/apps/baseapp.py
  nbgrader/apps/collectapp.py
  nbgrader/apps/dbapp.py
  nbgrader/apps/fetchassignmentapp.py
  nbgrader/apps/fetchfeedbackapp.py
  nbgrader/apps/listapp.py
  nbgrader/apps/releaseassignmentapp.py
  nbgrader/apps/releasefeedbackapp.py
  nbgrader/apps/submitapp.py
  nbgrader/docs/source/exchange/exchange_api.rst
  nbgrader/docs/source/exchange/exchange_plugin.rst
  nbgrader/docs/source/exchange/index.rst
  nbgrader/docs/source/index.rst
  nbgrader/exchange/__init__.py
  nbgrader/exchange/abc/__init__.py
  nbgrader/exchange/abc/collect.py
  nbgrader/exchange/abc/exchange.py
  nbgrader/exchange/abc/fetch.py
  nbgrader/exchange/abc/fetch_assignment.py
  nbgrader/exchange/abc/fetch_feedback.py
  nbgrader/exchange/abc/list.py
  nbgrader/exchange/abc/release.py
  nbgrader/exchange/abc/release_assignment.py
  nbgrader/exchange/abc/release_feedback.py
  nbgrader/exchange/abc/submit.py
  nbgrader/exchange/default/__init__.py
  nbgrader/exchange/default/collect.py
  nbgrader/exchange/default/exchange.py
  nbgrader/exchange/default/fetch_assignment.py
  nbgrader/exchange/default/fetch_feedback.py
  nbgrader/exchange/default/list.py
  nbgrader/exchange/default/release_assignment.py
  nbgrader/exchange/default/release_feedback.py
  nbgrader/exchange/default/submit.py
  nbgrader/exchange/exchange_factory.py
  nbgrader/server_extensions/assignment_list/handlers.py
  nbgrader/server_extensions/formgrader/apihandlers.py
  nbgrader/server_extensions/formgrader/handlers.py
Labels: enhancement
