Repository jupyter/nbgrader, pull requests merged in 2021-03, with the labels that each got.

#1324 Ensure errors are written to cell outputs to prevent the autograder from awarding points for failed tests
  nbgrader/preprocessors/execute.py
  nbgrader/tests/apps/files/submitted-cheat-attempt-alternative.ipynb
  nbgrader/tests/apps/files/submitted-cheat-attempt.ipynb
  nbgrader/tests/apps/test_nbgrader_autograde.py
Labels: bugfix

#1376 Make preprocessors of generate assignment, autograde and generate feedback configurable
  nbgrader/converters/autograde.py
  nbgrader/converters/base.py
  nbgrader/converters/generate_assignment.py
  nbgrader/converters/generate_feedback.py
Labels: enhancement

#1381 find cell failure when stderr is used
  nbgrader/tests/test_validator.py
  nbgrader/validator.py
Labels: bugfix

#1388 Move from travis ci to github actions
  .github/workflows/test.yml
  .travis.yml
  azure-pipelines.yml
Labels: maintenance

#1420 Fix various SQLAlchemy errors and warnings
  nbgrader/alembic/versions/167914646830_added_task_cells.py
  nbgrader/alembic/versions/e43177bfe90b_added_course_table_and_relationships.py
  nbgrader/api.py
  nbgrader/tests/api/test_models.py
  setup.py
Labels: bugfix

#1419 Update releasing docs and tools
  nbgrader/docs/source/contributor_guide/releasing.rst
  tools/backport_pr.py
  tools/gh_api.py
Labels: docs, maintenance

#1422 Fix docs building
  .gitignore
  nbgrader/docs/source/api/gradebook.rst
  nbgrader/docs/source/api/models.rst
  nbgrader/docs/source/build_docs.py
  nbgrader/docs/source/clear_docs.py
  nbgrader/docs/source/conf.py
  nbgrader/docs/source/user_guide/autograded/bitdiddle/ps1/problem1.ipynb
  nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem2.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem2.html
  nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
  nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb
Labels: bugfix, docs
