Repository jupyter/nbgrader, pull requests merged in 2021-05, with the labels that each got.

#1437 Make converter exporter class configurable
  nbgrader/converters/base.py
Labels: enhancement

#1425 Use NBGRADER_VALIDATING env var during autograding
  nbgrader/converters/autograde.py
  nbgrader/docs/source/user_guide/faq.rst
  nbgrader/tests/apps/files/validating-environment-variable.ipynb
  nbgrader/tests/apps/test_nbgrader_autograde.py
  nbgrader/tests/apps/test_nbgrader_validate.py
  nbgrader/validator.py
Labels: enhancement

#1431 Add dependabot configuration
  .github/dependabot.yml
Labels: maintenance

#1443 Fix broken windows tests
  .github/workflows/test.yml
Labels: bugfix, maintenance

#1444 Remove continuous integration for python 3.6
  .github/workflows/test.yml
  setup.py
Labels: maintenance

#1438 Validate pre and post convert hooks
  nbgrader/converters/base.py
Labels: enhancement

#1446 Prepare for 0.6.2 release
  .github/workflows/test.yml
  .gitignore
  .travis.yml
  azure-pipelines.yml
  nbgrader/docs/source/build_docs.py
  nbgrader/docs/source/changelog.rst
  nbgrader/docs/source/clear_docs.py
  nbgrader/docs/source/conf.py
  nbgrader/docs/source/user_guide/autograded/bitdiddle/ps1/problem1.ipynb
  nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem2.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem2.html
  nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
  setup.py
Labels: backport pr, maintenance

#1450 Update autograding_resources.rst
  nbgrader/docs/source/user_guide/autograding_resources.rst
Labels: docs
