Repository jupyter/nbgrader, pull requests merged in 2022-06, with the labels that each got.

#1591 Backport PR #1590 on branch 0.7.x (Ensure html files aren't copied over from documentation)
  nbgrader/apps/quickstartapp.py
Labels: bug, bugfix

#1593 Pin traitlets dependency for 0.7.x
  setup.py
Labels: bug, bugfix, maintenance

#1596 Don't depend on qtconsole
  setup.cfg
Labels: maintenance

#1598 Fix mathjax in formgrade templates
  nbgrader/server_extensions/formgrader/handlers.py
  nbgrader/server_extensions/formgrader/templates/formgrade/index.html.j2
Labels: bug, bugfix

#1599 Backport PR #1598 on branch 0.7.x (Fix mathjax in formgrade templates)
  nbgrader/server_extensions/formgrader/handlers.py
  nbgrader/server_extensions/formgrader/templates/formgrade/index.html.j2
Labels: bug, bugfix

#1601 Fix demos for JupyterHub 2.0 and JupyterLab
  demos/Dockerfile
  demos/demo_multiple_classes/jupyterhub_config.py
  demos/demo_one_class_multiple_graders/jupyterhub_config.py
  demos/demo_one_class_multiple_graders/setup_demo.sh
  demos/demo_one_class_one_grader/jupyterhub_config.py
  demos/restart_demo.sh
  demos/utils.sh
Labels: bug, bugfix, maintenance

#1592 Change default exchange path
  demos/restart_demo.sh
  nbgrader/docs/source/user_guide/advanced.rst
  nbgrader/docs/source/user_guide/what_is_nbgrader.rst
  nbgrader/exchange/default/exchange.py
Labels: bug, bugfix

#1602 Add instruction to run playwright tests
  nbgrader/docs/source/contributor_guide/testing.rst
Labels: documentation

#1603 Use jupyter css variable in labextension to manage colors with theme
  style/assignment_list.css
  style/common.css
  style/course_list.css
  style/create_assignment.css
  style/validation_message.css
Labels: enhancement

#1606 Create assignment panel only open if a Notebook is visible on main area
  .github/workflows/test-labextensions.yml
  src/create_assignment/create_assignment_extension.ts
  src/create_assignment/index.ts
Labels: enhancement

#1608 Backport PR #1607 on branch 0.7.x (More informative error messages in ClearSolutions)
  nbgrader/preprocessors/clearsolutions.py
Labels: bug, bugfix

#1609 Prepare 0.7.1 release
  nbgrader/_version.py
  nbgrader/docs/source/changelog.rst
  nbgrader/docs/source/user_guide/autograded/bitdiddle/ps1/problem1.ipynb
  nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem2.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem2.html
  nbgrader/nbextensions/assignment_list/main.js
  nbgrader/nbextensions/course_list/main.js
  nbgrader/nbextensions/validate_assignment/main.js
Labels: maintenance

#1611 Pins selenium version to 4.2
  setup.cfg
Labels: maintenance

#1610 Fix version bumping for pre-releases
  .github/workflows/check-release.yml
  demos/restart_demo.sh
  nbgrader/_version.py
  nbgrader/docs/source/contributor_guide/installation_developer.rst
  nbgrader/nbextensions/assignment_list/main.js
  nbgrader/nbextensions/course_list/main.js
  nbgrader/nbextensions/validate_assignment/main.js
  pyproject.toml
  setup.cfg
  src/assignment_list/index.ts
  src/course_list/index.ts
  src/validate_assignment/index.ts
  tools/post-bump.py
Labels: maintenance

#1614 Fix missing `.` in the JS version
  tools/post-bump.py
Labels: maintenance

#1615 Automated Changelog Entry for 0.8.0a0 on main
  CHANGELOG.md
Labels: documentation

#1617 Move the jupyter_releaser hooks from package.json to pyproject.toml
  package.json
  pyproject.toml
Labels: maintenance
