Repository jupyter/nbgrader, pull requests merged in 2022-07, with the labels that each got.

#1620 Automated Changelog Entry for 0.8.0a1 on main
  CHANGELOG.md
Labels: documentation

#1621 Pin version of nbclassic<0.4.0
  setup.cfg
Labels: bug, bugfix

#1624 Automated Changelog Entry for 0.8.0a2 on main
  CHANGELOG.md
Labels: documentation

#1623 Fix some typo and variable declaration in labextension tests
  nbgrader/tests/labextension_ui-tests/tests/test_assignment_list.spec.ts
  nbgrader/tests/labextension_ui-tests/tests/test_course_list.spec.ts
  nbgrader/tests/labextension_ui-tests/tests/test_create_assignement.spec.ts
  nbgrader/tests/labextension_ui-tests/tests/test_formgrader.spec.ts
  nbgrader/tests/labextension_ui-tests/tests/test_utils.ts
  nbgrader/tests/labextension_ui-tests/tests/test_validate_assignment.spec.ts
Labels: maintenance

#1626 Feature/mybinder
  .github/workflows/binder.yaml
  MANIFEST.in
  binder/jupyter_config.json
  binder/postBuild
  binder/start
Labels: enhancement

#1647 Remove a remaining dependency to notebook
  nbgrader/server_extensions/assignment_list/handlers.py
Labels: maintenance, dependencies
