Repository jupyter/nbgrader, pull requests merged in 2022-05, with the labels that each got.

#1571 Add workflow to enforce GitHub labels
  .github/workflows/enforce-label.yml
Labels: maintenance

#1572 Fix a false positive test
  nbgrader/tests/nbextensions/test_create_assignment.py
Labels: bug

#1573 Prepare 0.7.0 release
  nbgrader/_version.py
  nbgrader/docs/source/changelog.rst
  nbgrader/docs/source/clear_docs.py
  nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem2.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem2.html
  nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb
  nbgrader/nbextensions/assignment_list/main.js
  nbgrader/nbextensions/course_list/main.js
  nbgrader/nbextensions/validate_assignment/main.js
Labels: maintenance

#1518 [converters/autograde] Fix autograded notebook permission
  nbgrader/converters/autograde.py
Labels: bugfix

#1576 Revert "[converters/autograde] Fix autograded notebook permission"
  nbgrader/converters/autograde.py
Labels: maintenance

#1582 Trivial typo: "int the database"
  nbgrader/apps/dbapp.py
Labels: documentation, maintenance

#1577 Set up jupyter releaser
  .github/workflows/check-release.yml
  .github/workflows/test.yml
  CHANGELOG.md
  MANIFEST.in
  dev-requirements.txt
  nbgrader/_version.py
  nbgrader/docs/source/changelog.md
  nbgrader/docs/source/changelog.rst
  nbgrader/docs/source/conf.py
  nbgrader/docs/source/contributor_guide/installation_developer.rst
  nbgrader/docs/source/contributor_guide/releasing.rst
  nbgrader/docs/source/user_guide/downloaded/ps1/archive/jupyter.png
  nbgrader/server_extensions/formgrader/static/components/bootstrap/README.md
  nbgrader/server_extensions/formgrader/static/components/datatables.net-bs/Readme.md
  nbgrader/server_extensions/formgrader/static/components/datatables.net/Readme.md
  nbgrader/server_extensions/formgrader/static/components/jquery/README.md
  nbgrader/tests/apps/files/jupyter.png
  nbgrader/tests/preprocessors/files/jupyter.png
  package.json
  pyproject.toml
  setup.cfg
  setup.py
  tasks.py
Labels: maintenance

#1579 Only add extra_template_basedirs if it has not been set
  nbgrader/converters/generate_feedback.py
Labels: bug

#1584 Update readthedocs-requirements.txt
  readthedocs-requirements.txt
Labels: bug, bugfix, documentation, maintenance

#1585 Backport PR #1579 on branch 0.7.x (Only add extra_template_basedirs if it has not been set)
  nbgrader/converters/generate_feedback.py
Labels: bug

#1587 Fix readthedocs automatic build
  .readthedocs.yaml
  MANIFEST.in
  readthedocs-requirements.txt
  readthedocs.yaml
Labels: documentation, maintenance

#1586 Jupyter server
  etc/jupyter/jupyter_notebook_config.json
  etc/jupyter/jupyter_server_config.d/nbgrader.json
  nbgrader/__init__.py
  nbgrader/exchange/abc/exchange.py
  nbgrader/server_extensions/assignment_list/__init__.py
  nbgrader/server_extensions/assignment_list/handlers.py
  nbgrader/server_extensions/course_list/__init__.py
  nbgrader/server_extensions/course_list/handlers.py
  nbgrader/server_extensions/formgrader/__init__.py
  nbgrader/server_extensions/formgrader/base.py
  nbgrader/server_extensions/formgrader/formgrader.py
  nbgrader/server_extensions/validate_assignment/__init__.py
  nbgrader/server_extensions/validate_assignment/handlers.py
  pyproject.toml
  setup.py
Labels: enhancement
