Repository jupyter/nbgrader, pull requests merged in 2023-09, with the labels that each got.

#1817 New Feature: Auto-generation of test code (compatible with 0.9.x)
  .gitignore
  nbgrader/apps/generateassignmentapp.py
  nbgrader/apps/quickstartapp.py
  nbgrader/converters/__init__.py
  nbgrader/converters/generate_assignment.py
  nbgrader/converters/generate_source_with_tests.py
  nbgrader/coursedir.py
  nbgrader/docs/source/user_guide/advanced.rst
  nbgrader/docs/source/user_guide/autotests.yml
  nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
  nbgrader/docs/source/user_guide/grades.csv
  nbgrader/docs/source/user_guide/images/autograder_tests_autogenerated_tests_jlab.png
  nbgrader/docs/source/user_guide/images/autograder_tests_autotest_jlab.png
  nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
  nbgrader/docs/source/user_guide/source/ps1_autotest/jupyter.png
  nbgrader/docs/source/user_guide/source/ps1_autotest/problem1.ipynb
  nbgrader/docs/source/user_guide/source/ps1_autotest/problem2.ipynb
  nbgrader/preprocessors/__init__.py
  nbgrader/preprocessors/clearsolutions.py
  nbgrader/preprocessors/instantiatetests.py
  nbgrader/tests/__init__.py
  nbgrader/tests/apps/files/autotest-hashed-changed.ipynb
  nbgrader/tests/apps/files/autotest-hashed-unchanged.ipynb
  nbgrader/tests/apps/files/autotest-hashed.ipynb
  nbgrader/tests/apps/files/autotest-hidden-changed-right.ipynb
  nbgrader/tests/apps/files/autotest-hidden-changed-wrong.ipynb
  nbgrader/tests/apps/files/autotest-hidden-unchanged.ipynb
  nbgrader/tests/apps/files/autotest-hidden.ipynb
  nbgrader/tests/apps/files/autotest-multi-changed.ipynb
  nbgrader/tests/apps/files/autotest-multi-unchanged.ipynb
  nbgrader/tests/apps/files/autotest-multi.ipynb
  nbgrader/tests/apps/files/autotest-simple-changed.ipynb
  nbgrader/tests/apps/files/autotest-simple-unchanged.ipynb
  nbgrader/tests/apps/files/autotest-simple.ipynb
  nbgrader/tests/apps/files/autotests.yml
  nbgrader/tests/apps/files/test-no-metadata-autotest.ipynb
  nbgrader/tests/apps/test_nbgrader_autograde.py
  nbgrader/tests/apps/test_nbgrader_generate_assignment.py
  nbgrader/tests/apps/test_nbgrader_generate_feedback.py
  nbgrader/tests/apps/test_nbgrader_quickstart.py
  nbgrader/tests/preprocessors/test_instantiatetests.py
  nbgrader/tests/ui-tests/assignment_list.spec.ts
  pyproject.toml
Labels: enhancement

#1823 Revert change breaking sqlalchemy 1.4.x
  nbgrader/api.py
Labels: bug, bugfix

#1824 Cleanup
  demos/demo_multiple_classes/jupyterhub_config.py
  demos/demo_one_class_multiple_graders/jupyterhub_config.py
  demos/formgrader_workspace.json
  demos/utils.sh
  nbgrader/server_extensions/assignment_list/handlers.py
  nbgrader/server_extensions/course_list/handlers.py
  nbgrader/server_extensions/formgrader/formgrader.py
  nbgrader/server_extensions/formgrader/handlers.py
  nbgrader/server_extensions/formgrader/static/js/manage_assignments.js
  nbgrader/server_extensions/formgrader/templates/formgrade/formgrade_macros.html.j2
  nbgrader/server_extensions/formgrader/templates/manage_assignments.tpl
  nbgrader/server_extensions/validate_assignment/handlers.py
  src/course_list/courselist.ts
  src/course_list/index.ts
  src/index.ts
Labels: maintenance

#1825 Backport PR #1823 on branch 0.8.x (Revert change breaking sqlalchemy 1.4.x)
  nbgrader/api.py
Labels: bug, bugfix

#1827 Labextension compatibility
  .github/workflows/test-extensions.yml
  package.json
  yarn.lock
Labels: maintenance, dependencies

#1807 Remove jupyter_notebook_config.json since notebook server is not supported anymore
  binder/jupyter_config.json
  etc/jupyter/jupyter_notebook_config.json
  pyproject.toml
Labels: maintenance
