Repository jupyter/nbgrader, pull requests merged in 2023-03, with the labels that each got.

#1741 Remove codecov badge
  README.md
Labels: bug, bugfix, maintenance

#1743 Remove the notification during UI tests, to fix a failing test
  nbgrader/tests/labextension_ui-tests/tests/test_assignment_list.spec.ts
  nbgrader/tests/labextension_ui-tests/tests/test_course_list.spec.ts
  nbgrader/tests/labextension_ui-tests/tests/test_create_assignement.spec.ts
  nbgrader/tests/labextension_ui-tests/tests/test_formgrader.spec.ts
  nbgrader/tests/labextension_ui-tests/tests/test_validate_assignment.spec.ts
Labels: maintenance

#1750 Upgrade python requirement
  .github/workflows/test-docs-python-nbextensions.yml
  .github/workflows/test-labextensions.yml
Labels: maintenance

#1760 Loosen the traitlets version requirement
  pyproject.toml
Labels: maintenance, dependencies

#1748 Unpin dependency on pytest and pytest-xdist
  pyproject.toml
Labels: maintenance, dependencies

#1764 Removes dependency to MarkupSafe<2.2.0
  pyproject.toml
Labels: maintenance, dependencies
