Repository jupyter/nbgrader, pull requests merged in 2023-08, with the labels that each got.

#1812 Update lab and notebook dependencies
  nbgrader/tests/ui-tests/utils/jupyter_server_config.py
  nbgrader/tests/ui-tests/utils/jupyter_server_config_notebook.py
  package.json
  pyproject.toml
  yarn.lock
Labels: maintenance, dependencies

#1811 Fix labextension plutin IDs in the docs
  demos/restart_demo.sh
  nbgrader/docs/source/user_guide/installation.rst
Labels: documentation

#1770 Add missing grade_cells before autograding
  nbgrader/preprocessors/overwritecells.py
  nbgrader/tests/preprocessors/test_overwritecells.py
Labels: bug, enhancement, bugfix

#1813 Backport PR #1770 on branch 0.8.x (Add missing grade_cells before autograding)
  nbgrader/preprocessors/overwritecells.py
  nbgrader/tests/preprocessors/test_overwritecells.py
Labels: bug, enhancement, bugfix

#1819 Fix jquery in documentation, and update documentation
  CHANGELOG.md
  nbgrader/docs/source/conf.py
  nbgrader/docs/source/user_guide/autograded/bitdiddle/ps1/problem1.ipynb
  nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem2.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem2.html
  nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
  nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb
  pyproject.toml
Labels: bug, bugfix, documentation
