Repository jupyter/nbgrader, pull requests merged in 2023-06, with the labels that each got.

#1756 Fix blank tab names and labextension button label
  src/assignment_list/assignmentlist.ts
  src/assignment_list/index.ts
  src/course_list/index.ts
  src/formgrader/index.ts
Labels: bug, bugfix

#1789 Fix selenium deprecation for nbextension tests
  nbgrader/tests/nbextensions/conftest.py
Labels: maintenance

#1790 Fix documentation links
  nbgrader/docs/make.bat
  nbgrader/docs/source/conf.py
  nbgrader/docs/source/configuration/jupyterhub_config.rst
  nbgrader/docs/source/contributor_guide/database.rst
  nbgrader/docs/source/contributor_guide/documentation.rst
  nbgrader/docs/source/contributor_guide/overview.rst
  nbgrader/docs/source/contributor_guide/pull_request.rst
  nbgrader/docs/source/contributor_guide/releasing.rst
  nbgrader/docs/source/plugins/zipcollect-plugin.rst
Labels: maintenance

#1730 Timeout configuration in validation and error message
  nbgrader/preprocessors/execute.py
  nbgrader/tests/apps/files/timeout.ipynb
  nbgrader/tests/apps/test_nbgrader_autograde.py
  nbgrader/tests/apps/test_nbgrader_validate.py
  nbgrader/validator.py
Labels: enhancement

#1775 Toggle visibility of all student names
  nbgrader/server_extensions/formgrader/static/js/gradebook_notebook_submissions.js
  nbgrader/server_extensions/formgrader/templates/gradebook_notebook_submissions.tpl
  nbgrader/tests/labextension_ui-tests/tests/test_formgrader.spec.ts
  nbgrader/tests/nbextensions/test_formgrader.py
Labels: enhancement

#1791 Pin sphinx<7
  pyproject.toml
Labels: maintenance

#1783 Check marking schemes for attachments to prevent leakage
  nbgrader/preprocessors/clearmarkingscheme.py
  nbgrader/tests/preprocessors/test_clearmarkscheme.py
Labels: enhancement

#1788 Upgrade to sqlalchemy>=2
  nbgrader/alembic/versions/167914646830_added_task_cells.py
  nbgrader/alembic/versions/e43177bfe90b_added_course_table_and_relationships.py
  nbgrader/api.py
  pyproject.toml
Labels: enhancement, maintenance
