Repository jupyter/nbgrader, pull requests merged in 2024-06, with the labels that each got.

#1893 Install the labextension in the correct directory
  pyproject.toml
  src/index.ts
Labels: maintenance

#1892 bump jupyterlab, notebook and ydoc dependencies
  package.json
  pyproject.toml
  src/common/validate.ts
  yarn.lock
Labels: maintenance

#1774 Make hashing independent of notebook content
  nbgrader/exchange/default/fetch_feedback.py
  nbgrader/exchange/default/list.py
  nbgrader/exchange/default/release_feedback.py
  nbgrader/exchange/default/submit.py
  nbgrader/tests/apps/files/submission_secret.txt
  nbgrader/tests/apps/files/submission_secret2.txt
  nbgrader/tests/apps/test_api.py
  nbgrader/tests/apps/test_nbgrader_list.py
  nbgrader/tests/apps/test_nbgrader_releasefeedback.py
  nbgrader/utils.py
Labels: bug, needs review, bugfix

#1859 Open formgrader with a local configuration file
  nbgrader/apps/baseapp.py
  nbgrader/docs/source/build_docs.py
  nbgrader/docs/source/configuration/nbgrader_config.rst
  nbgrader/server_extensions/formgrader/base.py
  nbgrader/server_extensions/formgrader/formgrader.py
  nbgrader/server_extensions/formgrader/handlers.py
  nbgrader/server_extensions/formgrader/templates/manage_assignments.tpl
  nbgrader/tests/ui-tests/formgrader.spec.ts
  package.json
  schema/formgrader.json
  src/index.ts
  yarn.lock
Labels: enhancement

#1890 Fixed LaTeX rendering in some demo notebooks
  nbgrader/docs/source/user_guide/autograded/bitdiddle/ps1/problem1.ipynb
  nbgrader/docs/source/user_guide/autograded/bitdiddle/ps1/problem2.ipynb
  nbgrader/docs/source/user_guide/autograded/hacker/ps1/problem1.ipynb
  nbgrader/docs/source/user_guide/autograded/hacker/ps1/problem2.ipynb
  nbgrader/docs/source/user_guide/downloaded/ps1/archive/ps1_hacker_attempt_2016-01-30-20-30-10_problem1.ipynb
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem2.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem1.html
  nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem2.html
  nbgrader/docs/source/user_guide/release/ps1/problem1.ipynb
  nbgrader/docs/source/user_guide/release/ps1/problem2.ipynb
  nbgrader/docs/source/user_guide/source/header.ipynb
Labels: documentation
