Repository jupyter/nbgrader, pull requests merged in 2024-10, with the labels that each got.

#1928 Upgrade upload-artifact action
  .github/workflows/check-release.yml
  .github/workflows/test-extensions.yml
Labels: maintenance

#1927 Fix labextension plugin IDs in the docs and demos
  demos/restart_demo.sh
  demos/utils.sh
  nbgrader/docs/source/user_guide/installation.rst
Labels: documentation

#1667 groupshared feedback re-release fix
  nbgrader/exchange/default/release_feedback.py
Labels: bug, bugfix
